# Generated by Django 2.2.7 on 2019-11-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='buyerprofile',
            old_name='id',
            new_name='name',
        ),
    ]
