# Generated by Django 2.2.7 on 2019-11-23 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20191123_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='fuel_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel', to='supplier.FuelRequest'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
