# Generated by Django 2.2.7 on 2019-11-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20191123_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='fuel_request',
        ),
        migrations.RemoveField(
            model_name='fuelrequest',
            name='location',
        ),
        migrations.RemoveField(
            model_name='fuelupdate',
            name='location',
        ),
    ]
