# Generated by Django 2.2.7 on 2019-11-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieruserprofile',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='supplieruserprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplieruserprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='supplieruserprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplieruserprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='supplieruserprofile',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.SupplierProfile'),
        ),
    ]
