# Generated by Django 2.2 on 2019-11-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='buyer_profile_pics'),
        ),
    ]
